apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL for Let's Encrypt's production environment.
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # IMPORTANT: Replace this with your email address.
    # Let's Encrypt will use this to contact you about expiring certificates and other notices.
    email: mufid.sales@gmail.com
    
    # Name of a secret used to store the ACME account's private key.
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
      
    # Configure the solver for the HTTP-01 challenge.
    # This will create temporary pods and ingress rules to prove domain ownership.
    solvers:
    - http01:
        ingress:
          # This must match the ingress class you are using.
          class: alb
